### ISSUE TITLE
global scope of compute_context

### ISSUE THREAD

**Issue by jingpengwu** [JuliaGPU/GPUArrays.jl#1]
I am curious that how would the global compute_context be access and set from backend? in the case that backend is also a module.

In the documentation of julia:
http://docs.julialang.org/en/release-0.4/manual/variables-and-scoping/#global-scope

```
Each module introduces a new global scope, separate from the global scope of all other modules; there is no all-encompassing global scope
```

**Comment by SimonDanisch** [comment]
It should be pretty obvious now! Feel free to reopen if the question still remains!
