### ISSUE TITLE
Broadcast with wrapper types

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/GPUArrays.jl#104]
```
julia> xs = cu([1,2,3])
3-element CuArray{Float32,1}:
 1.0
 2.0
 3.0

julia> xs .* xs'
ERROR: Arrays type contains pointer - this doesn't work on the GPU (So arrays that don't contain pointers to memory, e.g. UnitRanges, would work).
            Try converting it to a gpu array. Found: RowVector{Float32,CuArray{Float32,1}}
```

This is with CuArray's own broadcast kernel disabled.

(note that it's not enough to fix this for `RowVector`; we need something that new wrapper types can hook into).

**Comment by SimonDanisch** [comment]
Can you propose a solution? You seem to already handle this correctly in CuArrays ;)

**Comment by MikeInnes** [comment]
We need to convert host GPU arrays to device arrays using adapt. e.g. using CUDAnative vocabulary:

```julia
adapt_(::Type{CuDeviceArray}, x::CuArray) = x.buf
cudaconvert(x) = adapt(CuDeviceArray, x)
```

This is defined on RowVector so it should pass through OK.

I do handle this in CuArrays currently, but it's somewhat of a hack where I overload `cudaconvert` case by case.

**Comment by SimonDanisch** [comment]
Ok Fair enough! Should we just run something like `adapt(GPUDevice, arg)` over all arguments?
Or maybe better figure out what device we're targeting and then do e.g. `adapt(CUDevice, arg)`.

**Comment by MikeInnes** [comment]
Right, this should probably happen at kernel launch time (e.g. `cudaconvert` already gets called by CUDAnative when you do this). It's more a case of removing the check from `broadcast`, I think.

**Comment by SimonDanisch** [comment]
Makes sense!

**Comment by SimonDanisch** [comment]
Can you confirm the fix is as simple as: https://github.com/JuliaGPU/GPUArrays.jl/pull/105
I'm currently on windows without cudanative :(

**Comment by SimonDanisch** [comment]
Ok, seems to work for me after supporting RowVector in CLArrays!

**Comment by MikeInnes** [comment]
The fix looks right to me, so I guess we just need to make sure both backends are using `adapt` for device conversion. Can you take a look at that for CLArrays?
