### ISSUE TITLE
Broadcast still doesn't catch many cases

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/GPUArrays.jl#107]
One example is
```julia
julia> using Flux, CuArrays

julia> cu(Flux.onehotbatch(1:5,1:5));

julia> float.(ans); # falls back to base
```

I think that using `containertype` here (as in [CuArrays](https://github.com/JuliaGPU/CuArrays.jl/blob/48e1840ce7ac45837d6b3a20482f324a90a89885/src/broadcast.jl#L42)) would be more robust, and allow wrapper types to buy into GPU array broadcasting.

**Comment by SimonDanisch** [comment]
Yeah, that's the way to go!

**Comment by maleadt** [comment]
This works nowadays, without scalar iteration.

```
julia> CuArrays.allowscalar(false)

julia> cu(Flux.onehotbatch(1:5,1:5));

julia> float.(ans)
5×5 CuArray{Float64,2,Nothing}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0
```
