### ISSUE TITLE
Fails to load on OS X due to CLFFT, CLBLAS, CUDArt build errors

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaGPU/GPUArrays.jl#11]
Hey there! I wanted to test out GPUArrays given that it's had its first 0.0.1 release (congrats!), but ran into some trouble. I tried pulling down `ddfc16d` on OS X on Julia 0.6, and received build errors for CLFFT, CLBLAS (`OS X not officially supported`), and CUDArt (`@windows not defined`). GPUArrays still installed, however attempting to load it with `using GPUArrays` fails with `could not open file .../.julia/v0.6/GPUArrays/src/backends/supported_backends.jl`. Here's my versioninfo:
```
julia> versioninfo()
Julia Version 0.6.0-pre.alpha.0
Commit 29bc2ac* (2017-02-28 13:15 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

I'm wondering if there's any easy way around these errors, or if I'll need to manually build CLFFT and CLBLAS (as their errors point me to do on OS X), and somehow manually patch or remove the CUDArt dependency?

Regardless of these issues, you've done some amazing work so far!

**Comment by SimonDanisch** [comment]
Thanks!  :) 
Do you actually have an nvidia card? If yes, you might need to checkout the newest CUDArt version.
Also, you need to run Pkg.build("GPUArrays") and after that, all non functional backends shouldn't be included anymore! If you still get an error, let me know, best with a Pkg.status() report attached!

**Comment by jpsamaroo** [comment]
Unfortunately I do not, as I am a die-hard AMD fanboy :D
That said, I just ran `Pkg.build("GPUArrays")` (and installed Transpiler.jl after it gave me an error), which seems to have worked! The example at the end of the Readme is working, so I'll consider the build successful. Thanks!

**Comment by SimonDanisch** [comment]
Great :) what was the error with transpiler?!

**Comment by SimonDanisch** [comment]
Oh, I see... Transpiler isn't in the REQUIRE :D

**Comment by jpsamaroo** [comment]
Oh yeah sorry, I should have mentioned that!

**Comment by SimonDanisch** [comment]
No worries, it's now included :)
