### ISSUE TITLE
gpu_call blocks + threads

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGPU/GPUArrays.jl#133]
We should pass those to `gpu_call` on 0.7 via kw_args.
Can't make a PR right now (probably not a very smart idea before everything works anyways)
So just want to track this here!

**Comment by SimonDanisch** [comment]
Why? I prefer using functions when possible - especially when the actual interface is a function that gets overloaded for different scenarios!

**Comment by SimonDanisch** [comment]
Why? I prefer using functions when possible - especially when the actual interface is a function that gets overloaded for different scenarios!

**Comment by maleadt** [comment]
Because then it resembles more like a function call, which it is, instead of invoking a function, passing along a function value and a tuple of arguments. It's also proven valuable to do argument conversions before we hit the compiler.

**Comment by maleadt** [comment]
> We should pass those to gpu_call on 0.7 via kw_args.

Done :smile:
