### ISSUE TITLE
Wrapping gpuarrays in structs

### ISSUE THREAD

**Issue by rafaqz** [JuliaGPU/GPUArrays.jl#160]
It seems that passing structs with a field that is a GPUArray into a GPUArrays broadcast isn't possible. I'm just wondering what the reason for this is, an if it is a permanent situation.

My use case is users passing in arbitrary lists of raster layer arrays with additional metadata to go with each array, and a type to dispatch on to use them. Interestingly this solution works fine using tuples, but it's kinda weird, especially when the main use case is not even using GPUArrays, but shares the code:

```julia
array1 = CuArray(zeros(Int64, 10, 10))
array2 = CuArray(zeros(Int64, 10, 10))
struct DispatchType end
dispatchable_array = (DispatchType()), array2, 30)

dispatch_it(val, (_, array, metadata)::Tuple{DispatchType, AbstractMatrix, Number}, index, t::Number) = dosomething(val, array, metadata)

broadcast(dispatch_it, array1, (dispatchable_array,))
```

Why are tuples allowed to contain arrays, but structs are not? 

I'm also wondering wether to just do everything like this, and write a few macros/constructors to make it simpler.

**Comment by vchuravy** [comment]
If you define [`cudaconvert`](http://juliagpu.github.io/CUDAnative.jl/stable/lib/compilation.html#CUDAnative.cudaconvert) for your struct it will be converted at the call boundary.

```
struct X{T}
  x::T
end

cudaconvert(X) = X(cudaconvert(X.x))
```

**Comment by rafaqz** [comment]
Oh thanks I missed that. Maybe it should be in the docs that you need to manually convert all the fields of a struct.

Does a tuple work because `cudaconvert()` is called recursively on its fields?

**Comment by vchuravy** [comment]
Yes :) https://github.com/JuliaGPU/CUDAnative.jl/blob/8f48eaac2c3898c68803deb77e7a73573af10fc3/src/execution.jl#L19

A doc PR to CuArrays.jl would be most welcome!
