### ISSUE TITLE
Update syntax for Julia 1.0 

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaGPU/GPUArrays.jl#164]
- [x] `JLArray{Float32}(3, N) `-> `JLArray{Float32}(undef, 3, N)`
- [x] `A[1,:] = 1` -> `A[1,:] .= 1`

See also https://github.com/JuliaGPU/CuArrays.jl/issues/153

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/GPUArrays.jl/pull/309
