### ISSUE TITLE
Docs page not found

### ISSUE THREAD

**Issue by mohamed82008** [JuliaGPU/GPUArrays.jl#175]
It seems the docs link https://juliagpu.github.io/GPUArrays.jl/latest/ gives a page not found.

**Comment by maleadt** [comment]
Fixed in https://github.com/JuliaGPU/GPUArrays.jl/commit/fef24218b1d004b9d15caeecc7670f00ddcf362f: https://juliagpu.github.io/GPUArrays.jl/dev/
