### ISSUE TITLE
mapreduce of `view(GPUArrays)` dispatches to CPU

### ISSUE THREAD

**Issue by sw2030** [JuliaGPU/GPUArrays.jl#182]
As the title says mapreduce over a view goes to the CPU since the type-constraints are for `GPUArray`

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/GPUArrays.jl/blob/79cc61b1752523ce8386fe2904cc51a27e187c26/src/host/mapreduce.jl#L7-L8 uses AnyGPUArray now.

```
julia> CUDA.allowscalar(false)

julia> typeof(view(CUDA.rand(10,10),2:5,2:5))
SubArray{Float32, 2, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}

julia> sum(view(CUDA.rand(10,10),2:5,2:5))
7.5819764f0
```
