### ISSUE TITLE
GPUArrays and BigFloat enhancement?

### ISSUE THREAD

**Issue by protogeezer** [JuliaGPU/GPUArrays.jl#189]
I would like advice on how to proceed with an enhancement to Julia and GPU arrays. I'd like to figure out how to speed up (if possible) BigFloat performance - perhaps at first for a subset of BigFloat like Float128. My first thought is to try rewriting MPFR routines directly in Julia to avoid the ccall overhead. It would be even better if the Julia implementation would then also "just work" with GPUArrays. Any advice on whether this is a worthwhile endeavor would be greatly appreciated.

**Comment by vchuravy** [comment]
https://github.com/JuliaMath/DoubleFloats.jl might work already on the GPU (or it should be feasible to make it support GPU execution.) BigFloat in general is more tricky since the arbitrary precision does require dynamic memory allocations and that effectively needs GC support.

**Comment by protogeezer** [comment]
Tricky is OK. DoubleFloats are certainly interesting - thanks for pointing that out. It appears that DoubleFloats is written in Julia - thus maybe their performance is indicative of the order of magnitude speedup one might get over mpfr-based BigFloats? I’m interested in a faster IEEE binary128 for interoperability with other software in addition to a bit more precision and range.

Wouldn’t a special/first case of quad precision, e.g., eliminate the need for the dynamic allocations? If not, then perhaps limiting the GPUArrays support to GPUs with unified CPU/GPU VM? Assuming that the result array can be preallocated, I would think I could get something to work.

Stephen

**Comment by vchuravy** [comment]
Since there are very few hardware implementation of Float128 around (and non of them on GPUs) one will have to do a software implementation. Making that GPU compatibile is mostly a question of avoiding allocations and minimizing control-flow. I am going to close this because GPUArrays themselves are not the right place to implement. There is https://github.com/JuliaMath/Quadmath.jl but that depends on a C-library.
