### ISSUE TITLE
Question about B-S benchmark

### ISSUE THREAD

**Issue by AStupidBear** [JuliaGPU/GPUArrays.jl#19]
I'm interested to know why CLContext is 10 times slower than CUContext on the same GeForce GTX 950.

**Comment by SimonDanisch** [comment]
Me too :D  It'll take some time to figure out these things and fix them, and I currently don't have any time :(
But I'm pretty sure, that there is no reason why we shouldn't be able to match CUDAs speed with OpenCL.
I suspect it's some smart compiler optimization which opencl doesn't have, which we then have to manually apply... Or it's actually some performance bug, that I haven't found yet...

**Comment by maleadt** [comment]
Closing stale issue.
