### ISSUE TITLE
Different result for Array and GPUArrays with isapprox

### ISSUE THREAD

**Issue by jkozdon** [JuliaGPU/GPUArrays.jl#191]
The following MWE shows the issue:
```julia
using CuArrays
let
  A = ones(100)
  B = ones(100)
  B[1] += 2sqrt(eps(eltype(B)))
  @show A ≈ B
  @show A[1] ≈ B[1]
  @show CuArray(A) ≈ CuArray(B)
end
```
Which gives the following output
```
A ≈ B = true
A[1] ≈ B[1] = false
CuArray(A) ≈ CuArray(B) = false
```

GPUArrays uses a pointwise type comparison (see [mapreduce.jl](https://github.com/JuliaGPU/GPUArrays.jl/blob/8e19805091c7dd5e3d17eb5fee9fa70701c6615b/src/mapreduce.jl#L185-L194)) where each component must satisfy `isapprox`

The linear algebra package in the Julia Base uses an l2 like comparison (see [generic.jl](https://github.com/JuliaLang/julia/blob/c9777b0ab4db219f0721506d9cca2412e41408fa/stdlib/LinearAlgebra/src/generic.jl#L1435-L1449)]) where the relative tolerance is scaled by the norm of the vector.

There is also a discrepancy in how the pointwise `isapprox` is defined between GPUarrays and Julia base which is currently fixed by PR #190

**Comment by maleadt** [comment]
I'll just remove `isapprox`; all of JLArray/CuArray tests first copy back to the CPU anyway (and then rely on Base's `isapprox` definition).
