### ISSUE TITLE
Loads of possibly unnecessary deps

### ISSUE THREAD

**Issue by ranjanan** [JuliaGPU/GPUArrays.jl#2]
Hey, I was trying to install `GPUArrays`. I have a working version of CUDAnative. But after a Pkg.clone I find I need to have to installed the `GLAbstractions` and `GLFW` etc., Is it possible to decouple the package from all the backends so the user can simply use the backend he cares about?

**Comment by SimonDanisch** [comment]
Thats the plan in the long run ;) its not really functional right now
anyways. Lets see if we can lift it out of the prototype state soon!

**Comment by SimonDanisch** [comment]
Implemented!
