### ISSUE TITLE
0D broadcast always return a container: ArrayStyle{CuArray} breaks dispatch?

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/GPUArrays.jl#204]
I noticed an regression on 1.3 that, I think, stems from us wrongly using `Base.ArrayStyle`. Normally, [broadcast unwraps 0D containers](https://github.com/JuliaLang/julia/blob/2425ae760fb5151c5c7dd0554e87c5fc9e24de73/base/broadcast.jl#L803), thanks to [a method](https://github.com/JuliaLang/julia/blob/2425ae760fb5151c5c7dd0554e87c5fc9e24de73/base/broadcast.jl#L829) that dispatches on `ArrayStyle{0}`. However, we use `ArrayStyle{CuArray}`, not dispatching to this method in the 0D case, breaking dispatch (doubly-wrapping in a CuArray).

Array:

```julia
julia> a = Array{Float64}(undef)
0-dimensional Array{Float64,0}:
2.060653501812742e-115

julia> axes = ()
()

julia> bca = Broadcast.broadcasted(Base.:/, a, 0.5)
Base.Broadcast.Broadcasted(/, (2.060653501812742e-115, 0.5))

julia> typeof(bca)
Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0},Nothing,typeof(/),Tuple{Array{Float64,0},Float64}}

julia> copy(Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0}}(bca.f, bca.args, axes))
4.121307003625484e-115

julia> @which copy(Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0}}(bca.f, bca.args, axes))
copy(bc::Base.Broadcast.Broadcasted{#s627,Axes,F,Args} where Args<:Tuple where F where Axes where #s627<:Base.Broadcast.AbstractArrayStyle{0}) in Base.Broadcast at broadcast.jl:829
```

CuArray:

```julia
julia> x = CuArray{Float64}(undef)
0-dimensional CuArray{Float64,0}:
0.0

julia> bcx = Broadcast.broadcasted(Base.:/, x, 0.5)
Base.Broadcast.Broadcasted(/, (0.0, 0.5))

julia> typeof(bcx)
Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{CuArray},Nothing,typeof(/),Tuple{CuArray{Float64,0},Float64}}

julia> copy(Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{CuArray}}(bcx.f, bcx.args, axes))
0-dimensional CuArray{Float64,0}:
0.0

julia> @which copy(Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{CuArray}}(bcx.f, bcx.args, axes))
copy(bc::Base.Broadcast.Broadcasted{Style,Axes,F,Args} where Args<:Tuple where F where Axes) where Style in Base.Broadcast at broadcast.jl:836
```

Fallout:
```julia
julia> typeof(similar(bca, typeof(ra)))
Array{Float64,0}

julia> typeof(similar(bcx, typeof(rx)))
CuArray{CuArray{Float64,0},0}
```

Without having looked at our broadcast implementation in depth, I think we need a `CuArrayStyle{N} <: ArrayStyle{N}` (ref. `DefaultArrayStyle{N}`). @vchuravy IIRC you designed our current array style, do you have the time to take a look at this?

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/GPUArrays.jl/blob/b51001e552f203b09e76cbe4dd31a4c169a6f518/src/broadcast.jl#L9

So yeah...

**Comment by vchuravy** [comment]
Ah I suspected there was a reason for having the number of dimensions in there ;) Will take a look.
