### ISSUE TITLE
Incompatibility with FillArrays 0.7

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/GPUArrays.jl#216]
If this is not a strict requirement, perhaps the `FillArrays` requirement could be change to version `0` to allow all minor versions. Currently, this causes problems with any package that requires FillArrays 0.8 and the GPU stack.

**Comment by maleadt** [comment]
Or just add 0.8 support? FillArrays should probably tag 1.0 at some point.
Why do we even depend on that package? Is this just for the tests again?

**Comment by MikeInnes** [comment]
Yes, looking at it, seems like it's just a test dependency and could be removed entirely.

Adding 0.8 would have been fine, just figure it's unlikely that FillArrays changes will ever break our usage.

**Comment by maleadt** [comment]
We should just split GPUArrays in two and get rid dependencies like this and FFTW altogether. I'll have a look.

**Comment by MikeInnes** [comment]
Opened https://github.com/JuliaGPU/GPUArrays.jl/pull/217 for now.

**Comment by maleadt** [comment]
Fixed by https://github.com/JuliaGPU/GPUArrays.jl/pull/219
