### ISSUE TITLE
Compatibility with AbstractFFTs version 0.5.0?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaGPU/GPUArrays.jl#220]
Would it be possible to make GPUArrays compatible with AbstractFFTs version `0.5.0`?

**Comment by ssfrr** [comment]
Is it possible to tag a release with this fix? Currently folks who have GPUArrays.jl installed are having problems installing anything that requires FFTW. For example [this discourse post](https://discourse.julialang.org/t/how-to-play-an-audio-in-julia/31881/8)

**Comment by maleadt** [comment]
Yes, sorry, forgot about this. Tag incoming.

**Comment by maleadt** [comment]
https://github.com/JuliaRegistries/General/pull/6275

**Comment by DilumAluthge** [comment]
https://github.com/JuliaRegistries/General/pull/6275
