### ISSUE TITLE
logreg example does not want to work. + few qestions.

### ISSUE THREAD

**Issue by punkrediska** [JuliaGPU/GPUArrays.jl#26]
so i m runing on 0.6 julia, and exemple with ReverseDiff pkg. complains on convertion to pointer in GPUArray, is there a whay to fix it?

> LoadError: conversion to pointer not defined for GPUArrays.GPUArray{Float32,1,Array{Float32,1},GPUArrays.JLBackend.JLContext}
> while loading C:\Users\PunkR\.julia\v0.6\GPUArrays\examples\logreg.jl, in expression starting on line 23
> in gradient at ReverseDiff\src\api\gradients.jl:22
> in gradient at ReverseDiff\src\api\gradients.jl:24
> in seeded_reverse_pass! at ReverseDiff\src\api\tape.jl:47
> in seeded_reverse_pass! at ReverseDiff\src\api\utils.jl:31
> in reverse_pass! at ReverseDiff\src\tape.jl:87
> in reverse_exec! at ReverseDiff\src\tape.jl:93
> in special_reverse_exec! at ReverseDiff\src\derivatives/linalg\arithmetic.jl:224
> in A_mul_Bc! at base\linalg\matmul.jl:223
> in A_mul_Bt! at base\linalg\matmul.jl:193
> in gemm_wrapper! at base\linalg\matmul.jl:369
> in gemm! at base\linalg\blas.jl:1027

And 2nd question, is there some documentation about pakage? at least some kind of list of available functions?
And 3rd, in some benches there kind of NT = Base.Threads.nthreads() and JLBackend.init(), and i cant figure out how to set more threads, it's olweys find 1 availible/

> JLContext Intel(R) Xeon(R) CPU E5-1660 0 @ 3.30GHz with 1 

> threads

**Comment by ilkerkesen** [comment]
I am getting the same error, too.

**Comment by SimonDanisch** [comment]
1) I think the example was relying on a patch in ReverseDiff ..
2) Not yet, it's only whats in the readme!
3) You need to start Julia with `JULIA_NUM_THREADS=8 julia`.

**Comment by punkrediska** [comment]
Thanks, 
3. Thot addprocs() is kind of same with JULIA_NUM_THREADS...
2. Hope it's just yet heh.
1. Will you try to make supportable example of using ReverseDiff , or similar package with GPUArray?

**Comment by maleadt** [comment]
`gemm_wrapper` isn't part of GPUArrays anymore, but part of the library that implements the GPUArrays interface (e.g. CuArrays).
