### ISSUE TITLE
What is the compile_lib?

### ISSUE THREAD

**Issue by ilkerkesen** [JuliaGPU/GPUArrays.jl#29]
In CUDAnative backend, this package searches for a specific Julia source code file (library.jl) which is expected to be under CUDAdrv/examples/compilation. What's that file? I was getting an error due to this issue, but I think after I did run CUDAdrv tests, this error disappeared.

**Comment by jekbradbury** [comment]
It's been moved from CUDAdrv to CUDArt -- I assume that we just need to change the Pkg.dir call to point there?

**Comment by SimonDanisch** [comment]
Should work again in #37
