### ISSUE TITLE
Remove type piracy on Adapt?

### ISSUE THREAD

**Issue by piever** [JuliaGPU/GPUArrays.jl#296]
I've noticed that this package is pirating methods from Adapt [here](https://github.com/JuliaGPU/GPUArrays.jl/blob/master/src/host/abstractarray.jl#L48). Is there a reason why that method can't go in Adapt?

**Comment by maleadt** [comment]
That functionality isn't meant to be general-purpose, it's just to implement `convert_to_cpu`, so we should probably use a locally-defined adaptor.
