### ISSUE TITLE
Features we need

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGPU/GPUArrays.jl#30]
* notify julia's GC of GPU memory pressure
     * could do this as a first approach: look up free mem in GPUArray constructor and call gc if almost full
     * memory manager (Grab one big buffer?! Grow a buffer? Reuse stuff? Work on only few arrays and make that fast? reuse [KnetArrays](http://denizyuret.github.io/Knet.jl/latest/reference.html#KnetArray-1) approach?)
* views: treat everything as a view into gpu memory. `setindex!` / `getindex` view or not? 
* mapreduce dim
* concatenating / slicing
* stencil operations

@denizyuret, @ilkerkesen

**Comment by SimonDanisch** [comment]
@one_more_minute, @vchuravy @maleadt

**Comment by MikeInnes** [comment]
Would be great to make any custom memory management / pooling its own reusable piece. I made a start with [Deadpool](https://github.com/MikeInnes/Deadpool.jl), but that's ridiculously naive right now.

**Comment by maleadt** [comment]
This is stale; let's close it.
