### ISSUE TITLE
indirect indexing with views gives scalar indexing

### ISSUE THREAD

**Issue by guyvdbroeck** [JuliaGPU/GPUArrays.jl#313]
This code used to work without scalar indexing: 
```
julia> i = CuArray(UInt[1 2 3 1 2;0 0 0 0 0]);

julia> x = CuArray([1.0,2.0,3.0]);

julia> x[i[1,:]];

julia> @views x[i[1,:]];
ERROR: scalar getindex is disallowed
```

**Comment by maleadt** [comment]
I don't think this has ever worked, or at least not intentionally. Note that the scalar iteration comes from the bounds checking, and we'll now perform a memory copy (so for performance you want to avoid that check).

For future issues, please include the actual stack trace.
