### ISSUE TITLE
Initializing Second Device

### ISSUE THREAD

**Issue by jekyllstein** [JuliaGPU/GPUArrays.jl#38]
Initializing a backend such as opencl it selects the first device by default as seen in lines 29-38 of opencl.jl
[https://github.com/JuliaGPU/GPUArrays.jl/blob/master/src/backends/opencl/opencl.jl](url)
```julia 
dev = if isempty(devlist)
                devlist = cl.devices(:cpu)
                if isempty(devlist)
                    error("no device found to be supporting opencl")
                else
                    first(devlist)
                end
            else
                first(devlist)
            end
```

Can we add functionality to select from multiple supported devices when initializing.  For example, most laptops with discrete graphics also have integrated graphics as an option.  For these computers the first device is the integrated chip which is normally not what you want to use doing GPU acceleration.

**Comment by NHDaly** [comment]
Not sure how the maintainers feel about this issue, but it affects me as well. I've started a small PR for the OpenCL context at #39.
