### ISSUE TITLE
Compatibility with FillArrays

### ISSUE THREAD

**Issue by st--** [JuliaGPU/GPUArrays.jl#381]
We are trying to provide [GPU support for AbstractGPs.jl](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/pull/197). In AbstractGPs we make use of [FillArrays.jl](https://github.com/JuliaArrays/FillArrays.jl), which unfortunately results in CPU Matrix results when combined with e.g. a CuArray. Would be great if GPUArrays.jl could provide support for the FillArray types!

**Comment by maleadt** [comment]
Could you provide an MWE of what doesn't work, and what you would want to work?

**Comment by st--** [comment]
MWE:
```julia
using FillArrays, CUDA, Test
@test CUDA.rand(3, 3) + Fill(1.2, 3, 3) isa AbstractGPUArray  # works as expected
@test_broken CUDA.rand(3,3) + Diagonal(Fill(1.2, 3)) isa AbstractGPUArray  # would expect this to work, too
```

**Comment by st--** [comment]
I just became aware of https://github.com/JuliaArrays/FillArrays.jl/pull/165/files, it might fix this issue? but I haven't checked it yet.

**Comment by maleadt** [comment]
Sorry for the slow response.

> @test_broken A + Diagonal(Fill(1.2, 3)) isa AbstractGPUArray  # would expect this to work, too

That's because you nest the Fill in a Diagonal; we can't have dispatch for every combination of nested wrappers. See https://github.com/JuliaGPU/Adapt.jl/issues/21, this needs support in Base (e.g. https://github.com/JuliaLang/julia/pull/31563) for better support.
