### ISSUE TITLE
mapreduce broken for empty arrays

### ISSUE THREAD

**Issue by danielwe** [JuliaGPU/GPUArrays.jl#398]
mapreduce and functions that build upon it return nonsense when called on empty arrays. MWE:

```julia
using CUDA

maximum(cu(Float32[]))
# e.g., 52237.227f0

sum(abs, cu(Float32[]))
# e.g., 10732.34f0
```

The issue seems to be that when reducing over an empty array, the following line allocates a return array of length 1:

https://github.com/JuliaGPU/GPUArrays.jl/blob/6e47ff5555765bff3215fdb1c0cb60e310bb7db1/src/host/mapreduce.jl#L64

If I understand correctly, the single element in this array is never initialized or written to but is what ends up being returned.

Not sure what the correct solution to every edge case woudl be, but for reference, Base varies between returning a neutral element and throwing an error depending on the reduction and eltype (which mostly makes sense, e.g., returning 0 for an empty sum, but weirdly they also return 0 for an empty reduction with max while throwing for an empty reduction with min).

**Comment by danielwe** [comment]
Great! This is a lot better than returning uninitialized data. However things like `maximum(empty) == typemin(eltype(empty))` is perhaps a little aggressive? Looking deeper into what Base does, it generally throws an error for empty reductions unless `init` is explicitly passed. There are a handful of special-cased exceptions that work without `init`, which are mostly just variants of `sum` and `prod`, plus `mapreduce(abs, max, empty)` (the `abs` is key). You can see the whole list here:

https://github.com/JuliaLang/julia/blob/aa1bd283cc6ef2a02cf47ccd29903a800f0f77c4/base/reduce.jl#L311-L374

**Comment by maleadt** [comment]
> However things like `maximum(empty) == typemin(eltype(empty))` is perhaps a little aggressive?

Yeah, we currently try to guess an appropriate `init` (which is `typemin` for `minimum`) because of how the GPU reduction always needing one (i.e., even in the non-empty case). I'm not particularly happy about that... The alternative is that we require an explicit initializer every time an empty input is passed, but Base doesn't do that (`sum(Int[]) == 0`). And it would be annoying to go about specializing individual reductions...

Thoughts?

**Comment by danielwe** [comment]
Yeah, as I showed, Base goes through the pain of special-casing the ones that are considered unambiguous (empty sums and products and a few more) while requiring `init` in the general case. If that's too much hassle (strong sympathy with that!) then I think I lean slightly towards always requiring `init`, but that's not a strongly held opinion.

**Comment by maleadt** [comment]
Ideally we'd reuse `reduce_empty`.
