### ISSUE TITLE
JLArray <: AnyCuArray == false

### ISSUE THREAD

**Issue by MilkshakeForReal** [JuliaGPU/GPUArrays.jl#423]
I'm testing with `JLArrays`. It looks like some linear algebra operations do not recognize JLArray.

```julia
julia> @which dot(jl([1,2]),jl([3,4]))
dot(x::AbstractArray, y::AbstractArray) in LinearAlgebra at C:\Users\Luffy\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\LinearAlgebra\src\generic.jl:907
```

**Comment by maleadt** [comment]
I'm not sure what you're trying to show with that code listing. And wrt. the title, JLArray indeed is no Any*Cu*Array.

We're running all the GPUArrays tests with JLArrays, so please include more details about the issue.

**Comment by MilkshakeForReal** [comment]
It means `dot`, for example, will not pass the tests

**Comment by maleadt** [comment]
What tests? `dot` is not implemented in GPUArrays.jl, only by CUDA.jl. There's no relation between JLArray and CuArray (or derived type aliases like AnyCuArray), so functionality from CUDA.jl isn't expected to work like that. If you want `dot` to work on JLArrays, you need a generic implementation in GPUArrays which you may or may not be able to port from packages like CUDA.jl (but for this specific operation it's only implemented in terms of CUBLAS, i.e. non-generically, which is also the reason the implementation doesn't live here in the first place).

---

Off topic: please put some more effort into issues you open. Here, you've opted for a nondescriptive title, provided no version information or other means reproduce like a MWE, and not even shown the actual issue or error. This is not productive, and only makes it more difficult for people to respond or look into your issue.

**Comment by MilkshakeForReal** [comment]
I have made the problem very clear, JLArrays cannot be used to test the functions defined in CUDA. You seem to understand the problem well, why do you assume that there is a problem beyond this scope?
I don't like to be long-winded, but rather concise. Version information is useless information for this problem.

**Comment by maleadt** [comment]
JLArray and CUDA/CuArray are unrelated; there's no compatibility guarantee between CUDA.jl's `dot` and GPUArrays. I don't know what more to say. Feel free to remain unhelpfully 'concise', but know that this is not how you interact with an open-source project.

**Comment by MilkshakeForReal** [comment]
> there's no compatibility guarantee between CUDA.jl's dot and GPUArrays

This satisfies an answer. Please go straight to the point. I find it unproductive to extract useful information from your long-winded ramblings.
