### ISSUE TITLE
Error from `CuMatrix * Diagonal` on Julia 1.8

### ISSUE THREAD

**Issue by mcabbott** [JuliaGPU/GPUArrays.jl#426]
This came up in the tests for ChainRules, which failed as soon as 1.8 was released. There it occurs using JLArrays, but I've checked the same happens for CUDA. 
```julia
julia> using CUDA, LinearAlgebra

julia> CUDA.allowscalar(false)

julia> Diagonal(cu(rand(3))) * cu(rand(3,3)) isa CuArray
true

julia> cu(rand(3,3)) * Diagonal(cu(rand(3))) isa CuArray
ERROR: Scalar indexing is disallowed.
```
I believe this fails on 1.9 (nightly) too, but didn't check CUDA there, only JLArrays. (Masked by other failures in CR's tests on nightly.)

Edit: Closed by #425 , I see now

**Comment by maleadt** [comment]
Should be fixed, let's tag a release.
