### ISSUE TITLE
Illegal memory access when building dense matrix

### ISSUE THREAD

**Issue by GVigne** [JuliaGPU/GPUArrays.jl#439]
Hi!
I was playing around with computations using a lot of memory and ran into some sort of CUDA error I can't quite understand. This might be a CUDA bug: if it's the case, I'll transfer this issue to the CUDA.jl package. The only GPU I have is a NVIDIA one, so I can't test this on other devices to reproduce it.

Here is a MWE:
```
julia> using CUDA
julia> using LinearAlgebra
julia> CuMatrix{Float32}(I, 135515, 310)

ERROR: CUDA error: an illegal memory access was encountered (code 700, ERROR_ILLEGAL_ADDRESS)
Stacktrace:
 [1] throw_api_error(res::CUDA.cudaError_enum)
   @ CUDA ~/Desktop/CUDA.jl/lib/cudadrv/libcuda.jl:27
 [2] macro expansion
   @ ~/Desktop/CUDA.jl/lib/cudadrv/libcuda.jl:35 [inlined]
 [3] cuCtxSynchronize
   @ ~/Desktop/CUDA.jl/lib/utils/call.jl:26 [inlined]
 [4] nonblocking_synchronize
   @ ~/Desktop/CUDA.jl/lib/cudadrv/context.jl:329 [inlined]
 [5] device_synchronize()
   @ CUDA ~/Desktop/CUDA.jl/lib/cudadrv/context.jl:319
 [6] top-level scope
   @ ~/Desktop/CUDA.jl/src/initialization.jl:157
```

I'm guessing this is an out of memory error, as running `CuMatrix{Float32}(I, 310, 310)` or `CuMatrix{Float32}(I, 10000, 310)` runs fine. Maybe at some point we try to build the entire matrix of size `(135515,135515)` which is way too much? 

The reason I am raising an issue here and not in CUDA.jl is that I was able to track down the function calls up to [here](https://github.com/JuliaGPU/GPUArrays.jl/blob/5789611939b9c59bbd374eed87e33ea2228134dd/src/host/construction.jl#L33-L38). The kernel which gets executed is [`identity_kernel`](https://github.com/JuliaGPU/GPUArrays.jl/blob/5789611939b9c59bbd374eed87e33ea2228134dd/src/host/construction.jl#L25-L31) which is not reimplemented/overloaded in CUDA.

What am I doing wrong? Since I can run `Array{Float32}(I, 135515, 310)` and that the resulting array is of a reasonable size (about 168 Mb), I thought I could do the same with my GPU.

**Comment by maleadt** [comment]
Thanks for the concise report! This is an issue with identity_kernel indeed, fix incoming.
