### ISSUE TITLE
Multiplying small Matrices 

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGPU/GPUArrays.jl#45]
We rely on Base to route A * B calls to the correct BLAS routines.
But base actually reroutes small matrices to a julia implementation here:

https://github.com/JuliaLang/julia/blob/master/base/linalg/matmul.jl#L336

We need to overload this and change the behaviour for GPUArrays.
I'm almost inclined to throw an error, since no one should actually multiply a 4x4 matrix on the GPU like that.
Ref: #44

**Comment by AustinPrivett** [comment]
If somebody is multiplying *many* small matrices together, e.g. something like

```julia
a = [randn(4,4) for i in 1:1000]
b = [randn(4,4) for i in 1:1000]
c = a .* b
```

then using GPUArrays could be helpful, correct? In such a case, we wouldn't want `a * b` for small matrices to throw an error.

**Comment by ChrisRackauckas** [comment]
You'd want to write your own kernel for that, but on a contiguous slab of GPU memory. 1000 probably still isn't enough for GPUs to be helpful.

**Comment by maleadt** [comment]
We implement `mul!` at a higher level now, so this shouldn't be a problem anymore.
