### ISSUE TITLE
Port subarray/reinterpret/reshape code from CUDA.jl

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/GPUArrays.jl#456]
CUDA.jl currently represents contiguoussubarrays, array reinterpretations, and reshapes, as instances of CuArray. That makes it much easier to interface with vendor libraries, because those don't care about array wrappers as long as you can get a pointer to memory. Since that applies to all GPU back-ends, I propose porting this code over from CUDA.jl so that we don't have to duplicate the tricky details of reinterpret, https://github.com/JuliaGPU/CUDA.jl/blob/868d33ea3067d6bb2403a9cf29d0f1214548314b/src/array.jl#L799-L908, or views, https://github.com/JuliaGPU/CUDA.jl/blob/868d33ea3067d6bb2403a9cf29d0f1214548314b/src/array.jl#L681-L744.

This would add an API requirement to all GPU back-ends, namely the ability to create multiple array instances that share a common buffer. If the buffer is separately garbage collected, this is trivial, e.g., https://github.com/JuliaGPU/Metal.jl/blob/e1d24bc7efdb9057cded8f425a3de925f7326e85/src/array.jl#L347-L351. To support early freeing, manual refcounting is needed, e.g., https://github.com/JuliaGPU/CUDA.jl/blob/868d33ea3067d6bb2403a9cf29d0f1214548314b/src/array.jl#L779-L794.

@jpsamaroo is this acceptable for AMDGPU.jl?

**Comment by jpsamaroo** [comment]
We use refcounting of the underlying buffer to track views and such, which is handled automatically when a new `ROCArray` wrapper is created: https://github.com/JuliaGPU/AMDGPU.jl/blob/5b095c893c58fb321d26976614b2a26859231810/src/array.jl#L65-L78. So far this seems to work nicely for encapsulating all the ugliness of refcounting and keep it in the `Mem` module as much as possible. We also separately track manual `unsafe_free!` from refcounting, allowing a buffer to become dead regardless of whether there are references around: https://github.com/JuliaGPU/AMDGPU.jl/blob/5b095c893c58fb321d26976614b2a26859231810/src/array.jl#L80.

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/GPUArrays.jl/pull/468
