### ISSUE TITLE
No dedicated tests for GPUArraysCore

### ISSUE THREAD

**Issue by ericphanson** [JuliaGPU/GPUArrays.jl#479]
I noticed GPUArraysCore doesn't have a `test` dir: https://github.com/JuliaGPU/GPUArrays.jl/tree/master/lib/GPUArraysCore. Is it fully tested via GPUArrays, or should it have its own tests too?

**Comment by maleadt** [comment]
It's fully tested via GPUArrays. In fact, I hope to get rid of GPUArraysCore as soon as the ecosystem has moved to package extensions (it's purely a loading latency workaround for when you need to depend on GPU packages), is why the package isn't really fleshed out.

**Comment by ericphanson** [comment]
Ok, thanks!
