### ISSUE TITLE
Broadcasting into CPU array of GPU arrays with `Ref(gpu array)` fails

### ISSUE THREAD

**Issue by ToucheSir** [JuliaGPU/GPUArrays.jl#505]
MWE:

```julia
using JLArrays

x = jl([1])
xs = [copy(x)]

julia> xs .= Ref(x)
ERROR: This object is not a GPU array
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] backend(#unused#::Type)
   @ GPUArraysCore ~/.julia/packages/GPUArraysCore/uOYfN/src/GPUArraysCore.jl:148
 [3] backend(x::Vector{JLArray{Float64, 1}})
   @ GPUArraysCore ~/.julia/packages/GPUArraysCore/uOYfN/src/GPUArraysCore.jl:149
 [4] _copyto!
   @ ~/.julia/packages/GPUArrays/dAUOE/src/host/broadcast.jl:70 [inlined]
 [5] materialize!
   @ ~/.julia/packages/GPUArrays/dAUOE/src/host/broadcast.jl:46 [inlined]
 [6] materialize!(dest::Vector{JLArray{Float64, 1}}, bc::Base.Broadcast.Broadcasted{JLArrays.JLArrayStyle{0}, Nothing, typeof(identity), Tuple{Base.RefValue{JLArray{Float64, 1}}}})
   @ Base.Broadcast ./broadcast.jl:881
 [7] top-level scope
   @ REPL[11]:1
```
It seems strange that this would hit the GPU array path, given that the destination container is a CPU array. The reason it appears to be doing so is that https://github.com/JuliaGPU/GPUArrays.jl/blob/7807069d1fcc843e4889df5600a2425c95fa8cb2/src/host/broadcast.jl#L36 is overriding the default array style when combined.

Digging through the git blame, I couldn't figure out why https://github.com/JuliaGPU/GPUArrays.jl/pull/240/commits/7807069d1fcc843e4889df5600a2425c95fa8cb2 was required as part of #240. The tests added at https://github.com/JuliaGPU/GPUArrays.jl/blob/15969e927fbf4695aa2c782f3a9a95b41250bffa/test/testsuite/broadcasting.jl#L160-L174 suggest that a singular GPU array should behave differently when wrapped in a Ref and then unwrapped during broadcasting than it does when no broadcasting is involved. This defies my own intuition around how broadcasting should work, but presumably there's a good reason for it? With some quick local testing, removing the `BroadcastStyle(::Type{Base.RefValue{AT}}) where {AT<:AbstractGPUArray}` line above only causes those 3 ref tests to fail for me locally.

**Comment by maleadt** [comment]
> a singular GPU array should behave differently when wrapped in a Ref and then unwrapped during broadcasting

It makes it possible to access different elements within an otherwise ordinary GPU broadcast kernel. For example, something contrived:

```
julia> lookup_table = jl(rand(10));

julia> broadcast(data, Ref(lookup_table)) do x, lookup_table
           lookup_table[x]
       end
100×100 JLArray{Float64, 2}:
 0.676698  0.895006  0.874047  0.685655  0.647906  0.169476  …  0.454418  0.454418  0.028151  0.874047  0.874047
```

I didn't however consider that this would be breaking the (legitimate) use case of broadcasting array objects into an array of arrays. I guess it's ambiguous whether broadcasting using (not unwrapped) GPU array objects should be done on the CPU or on the GPU?

**Comment by maleadt** [comment]
Maybe a better way of accomplishing the above is by keeping the array outside of the broadcast, so that there's no `Ref` used to determine the broadcast style:

```
julia> broadcast(data) do x
           lookup_table[x]
       end
```

That currently doesn't work, however.

**Comment by maleadt** [comment]
> That currently doesn't work, however.

Actually, putting it in a function correctly captures `lookup_table` as part of the broadcast function, making everything work. So I guess with that we would remove the Ref hack...
