### ISSUE TITLE
free memory, check memory status

### ISSUE THREAD

**Issue by davidbp** [JuliaGPU/GPUArrays.jl#51]
During the juliacon demo @SimonDanisch  seemed you use a `free` function. Yet that function is not imported when importing GPUArrays.  I have seen issue #30 but I am making a separate issue only for the memory problem.

I am experiencing some problems when using GPUArrays in a notebook. 

Out of curiosity I just copied the same code that was printing a nice `The kernel appears to have died. It will restart automatically`, into a file, and it runs just fine.

This is the code

```julia
using GPUArrays
using BenchmarkTools

sizes = [x for x in 100:100:1000];
cpu_times = Dict()
gpu_times = Dict()

println("\nCPU times")
for s in sizes
    X = rand(Float32,s,s);
    X_result = zeros(X);
    res_cpu = @elapsed A_mul_B!(X_result, X,X)
    println("size: ", s, " x ", s, " seconds: ", res_cpu, " seconds")
    #cpu_times[s] = mean(res_cpu.times)/10^6
end

println("\nGPU times")
for s in sizes
    X = rand(Float32,s,s);
    X_result = zeros(X);
    X_gpu = GPUArray(X);
    X_result_gpu = GPUArray(zeros(Float32,s,s));

    res_gpu = @elapsed A_mul_B!(X_result_gpu, X_gpu, X_gpu)
    println("size: ", s, " x ", s, " seconds: ", res_gpu, " seconds")
    #gpu_times[s] = mean(res_gpu.times)/10^6
end
```

I really don't know what is internally doing GPUArrays in the for loop.
For example in the following code

```julia
s = 100
 X = rand(Float32,s,s);
 X_result = zeros(X);
 X_gpu = GPUArray(X);

s = 200
 X = rand(Float32,s,s);
 X_result = zeros(X);
 X_gpu = GPUArray(X);
```
Is the first array freed? 

- Can we free an array at any moment using a `free` function?
- Can we check the current status of a device easily? (how much ram is available in my gpu) for example.

**Comment by maleadt** [comment]
This functionality is up to the package implementing the GPUArray interface, e.g. CuArrays which does automatic freeing.
