### ISSUE TITLE
Register a new version of JLArrays.jl

### ISSUE THREAD

**Issue by mtfishman** [JuliaGPU/GPUArrays.jl#562]
In https://github.com/ITensor/ITensors.jl/pull/1539 we are hitting the issue in `resize!` that was fixed by #546 (which is an issue I embarrassingly introduced in the first place in #533, so thank you @jipolanco for the fix), but it isn't included in a registered version of JLArrays.jl right now from what I can tell. @maleadt can you register a new version of JLArrays.jl so we can use that fix? Thanks!

**Comment by maleadt** [comment]
@JuliaRegistrator register subdir="/lib/JLArrays"
