### ISSUE TITLE
Execution difference between `opencl` backend and native Julia

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/GPUArrays.jl#63]
```
function power_method(M, v)
    T = eltype(v)
    for i in 1:100
        v = M*v        # repeatedly creates a new vector and destroys the old v
        v ./= T(norm(v))
    end
    
    return v, T(norm(M*v)) / T(norm(v))  # or  (M*v) ./ v
end

M = [2 1; 1 1.]
v = [1., 1]
MM = GPUArray(M)
vv = GPUArray(v)

# OpenCL backend on a K80
vec, val = power_method(MM, vv)
# => ([0.000285175, 2.02974], 1.4145115942187871)

vec, val = power_method(M, v)
# => ([0.850651, 0.525731], 2.618033988749895)
```

**Comment by SimonDanisch** [comment]
Can you try the threaded backend?

**Comment by vchuravy** [comment]
Threaded: `([0.850651, 0.525731], 2.618033988749895)`

**Comment by SimonDanisch** [comment]
Would you have time to test the intermediate steps and figure out which operation is wrong? I can take it from there ;) Wouldn't be surprised if its CLBLAS....

**Comment by vchuravy** [comment]
The offending line is.... [drumroll please]

```
GPUArray([1.0, 1.0]) ./ 3.605551275463989
```

Which gives me the exciting result;
```
GPUArray with ctx: OpenCL context with:
Device: CL Tesla K80
            threads: 1024
             blocks: (1024, 1024, 64)
      global_memory: 11995.578368 mb
 free_global_memory: NaN mb
       local_memory: 0.049152 mb
: 
2-element Array{Float64,1}:
 4.02986e-5
 1.0   
```

**Comment by vchuravy** [comment]
Also amusing is the result of `.*`, `./` and `.+`

**Comment by SimonDanisch** [comment]
Ah, can you try Float32... I should throw errors for Float64, which is currently not supported very well -.-

**Comment by vchuravy** [comment]
Only `Float32` works fine, but as soon as either the constant or the array is `Float64` things start to break.
Yeah errors are preferable over subtlety wrong results.

**Comment by jpsamaroo** [comment]
Is there any possibility of a "switch" to allow Float64 values to be silently converted to Float32 (maybe with a warning that this is occurring)? It makes sense for the default to throw an error, but there are also cases where, for ease of writing kernels without having to constantly add `f0` at the end of constants and such, automatic conversion would be useful.

Just an idea, let me know if this is a totally bad/unfeasible thing to do :)

**Comment by SimonDanisch** [comment]
Okay, added Float64 support in CLArrays  and error when device doesn't support Float64.
Hopefully i can merge all these changes very soon!

**Comment by maleadt** [comment]
Closing stale issue.
