### ISSUE TITLE
JLArrays are created on the GPU?

### ISSUE THREAD

**Issue by rveltz** [JuliaGPU/GPUArrays.jl#87]
Hi,

I want to take advantage of the threaded broadcast of your package but I ran into this:

```julia
using GPUArrays
a=JLArray(rand(10))
```

which gives:

```
GPU: 10-element Array{Float64,1}:
 0.709778
 0.691078
 0.974742
 0.546105
 0.962552
 0.737111
 0.297245
 0.985732
 0.495128
 0.496053
```

**Comment by SimonDanisch** [comment]
Hi,
sorry if it's not entirely clear, but JLArray is task based, so not threaded right now :( 
That it prints `GPU` is just the default for any GPU array - maybe I should overload that for JLArray!

**Comment by rveltz** [comment]
Ah!

It seems to me it was the previous behavior. If it was, did you keep the functionality somewhere?

**Comment by rveltz** [comment]
What I also meant is that it displays `GPU: 10-elements...` for an array `JLArray` that is not on the GPU...
