### ISSUE TITLE
Broadcast error

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/GPUArrays.jl#94]
Example from Flux:

```julia
julia> using Flux, CuArrays

julia> x = Flux.onehot(3, 1:5)
5-element Flux.OneHotVector:
 false
 false
  true
 false
 false

julia> y = cu(rand(5))

julia> x .+ y
ERROR: MethodError: Cannot `convert` an object of type Tuple{} to an object of type Tuple{UInt32}
This may have arisen from a call to the constructor Tuple{UInt32}(...),
since type constructors fall back to convert methods.
```

We rely on OneHotArrays pretty heavily in Flux, so this is a big issue for seamless GPU support.

This seems to happen for any custom `isbits` array type, e.g. `(1:5) .+ cu(rand(5))` fails also.

**Comment by SimonDanisch** [comment]
Ah, yeah, broadcast needs an overhaul - which I haven't done yet since 0.7 will change everything anyways ;)
But this should have an easy fix, I'll look into it!
